const ResourceStrings = {
    about: 'About',
    apply_now: 'Apply Now',
    description_gain: 'What you can gain from a hackathon',
    description_gain_1: 'You\'ll have <strong>access to the tools, workshops and high-tech hardware</strong> to help your ideas come to life.',
    description_gain_2: 'You’ll get to work with large corporations, experienced mentors and other talented people.',
    description_gain_3: '<strong>In just 24 hours</strong>, your concept becomes a solution that can change tomorrow.',
    description_learn: 'How do we facilitate learning?',
    description_learn_1: 'We host a set of workshops that will teach you the specific techniques you can use throughout the weekend to excel in your stream.',
    description_learn_2: 'It doesn’t end there!',
    description_learn_3: 'We have selected a group of motivated mentors who will guide you to success, cheer you on and share their knowledge with you.',
    hacker_stories: 'Hacker Stories',
    how_it_works: 'How it works',
    partners: 'Partners',
    faq: 'faq',
    faq_long: 'Frequently Asked Questions',
    answers: [
      'Why, yes there is! As an MLH member event, we must follow their Code of Conduct.',
      'StarterHacks is taking place from January 12 - 13, 2019 at the Science Teaching Complex and Quantum Nano Centre, University of Waterloo.',
      'Yes, you can! However, as of this moment, we cannot compensate you for travel.',
      'From AI-apps to curing procrastination! You have the freedom to hack on anything you desire! APIs and hardware will become available closer to the date. However, as StarterHacks is an MLH event member, you must follow their Code of Conduct.',
      'Student? Student! did I mention students? StarterHacks is to help students gain familiarity and experience with hackathons. All students in different in levels of education are welcome to apply to participate in StaterHacks 2019 Hackathon.',
      'We will help you find team members leading up to and during the event. Registration will also act as a mingle session for participants, Slack (which will be the main communication platform for the event) will also become helpful for introductions and finding yourself team members. StaterHacks has Workshops, Mentors and many more tools that are there specifically catered to your needs to help develop ideas for your hack!',
      'Unfortunately, StarterHacks mainly caters towards helping students experience and become acquainted with hackathons, we cannot have non student participants. However, feel free to come out on Sunday, January 13th to see the finished products, and if you would like to be a mentor please apply above. We thank you for your interest and hope that we can accommodate you in the future.',
      'A charger and updated laptop, with any hardware you want to work on (that we have not provided), a water bottle, comfortable clothes, yourself, and an inquiring, curious mind!'
    ],
    questions: [
      'Is there a Code of Conduct?',
      'When and where is StarterHacks happening?',
      'Can I attend if I live far away?',
      'What can I hack on?',
      'Who can apply?',
      'I don’t have an idea or a team, what do I do?',
      'I’m not a student, can I still attend?',
      'What do I need to bring?'
    ],
    contact: 'Contact',
    contact_color: '#6dc1dd',
    img_1_alt: 'First picture describing ',
    img_top_alt: 'Second picture describing ',
    img_2_alt: 'Third picture describing ',
    projects: 'Projects',
    sign_up: 'Sign Up',
    starterhacks: 'StarterHacks 2019',
    starterhacks_date: 'University of Waterloo - Date 2019 to Date 2019',
    starterhacks_header: 'First-time hackers. Real-life problems. Meaningful solutions.',
    stream_title: 'Your skill. Your stream. Your choice',
    stream_bussiness: 'Bussiness',
    stream_bussiness_desc: 'Put together a business plan, understand various funding approaches and hone your pitching skills.',
    stream_design: 'Design',
    stream_design_desc: 'Expand your skills in a full range of design areas including user experience, graphic and brand design.',
    stream_dev: 'Development',
    stream_dev_desc: 'Experiment with multiple APIs, hardware and new coding languages.',
    stream_follow: 'Create solutions for a problem that you are itching to solve in StarterHacks 2019!'
};

export default ResourceStrings;
